### ISSUE TITLE
Openscapes link is broken

### ISSUE THREAD

**Issue by lastew** [WildCoLab/WildCo-Resources#1]
Looks like the Openscapes link in the readme doesn't lead anywhere! Or perhaps it's a private file that I can't access?

**Comment by ChrisBeirne** [comment]
Broken for me too! @Mitch Fennell ***@***.***>  @Catcan you
remember what that was pointing too?

**Comment by ChrisBeirne** [comment]
@Cat Sun ***@***.***>

**Comment by mitch-fen** [comment]
Looks like the problem was because the openscapes page was on our repo as a .Rmd, not a .md file. I've changed it and updated the link as appropriate.
